[DRAFT] Migrate repositories: Move /cgo and /libase and adjust SAP/go-ase
SAP/go-ase pull request #160
Opened 2020-10-21 12:18 UTC by fwilhelm92

This pull-request serves the purpose of **continuous feedback** while working on the migration (thus, it is declared as draft).

Feel free to comment! 

TODO:
- [x] Remove files from sap/go-ase/libase and sap/go-ase/cgo
- [x] Move files from sap/purego to sap/
- [x] Rename package to `ase`
- [x] Adjust import paths, variables, and methods accordingly to sap/go-dblib
- [x] Fix style, e.g.: `err := method()` to `if err := method(); err != nil`
- [x] Update go.mod and go.sum
- [x] Update Makefile
- [x] Update Contributing
- [x] Update License
- [x] Update Readme 
- [ ] Add documentation
- [ ] Final check
- [ ] Change branch `master` to `main`

2020-11-04 10:05 UTC, ntnn requested changes

2020-11-04 12:17 UTC, fwilhelm92 commented on .github/workflows/ci.yml
> +          go-version: '^1.15'
To use the same go-version as declared in `go.mod`. Is it necessary?

2020-11-04 13:33 UTC, ntnn submitted a review, later dismissed

2020-11-10 12:52 UTC, ntnn submitted a review, later dismissed

2020-11-10 17:59 UTC, ntnn approved these changes

2020-11-17 11:29 UTC, ntnn submitted a review, later dismissed

2020-12-03 12:18 UTC, cb80 approved these changes

2020-12-03 12:22 UTC, merged